version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t fargate-local:latest .
      - docker tag flocal 296274010522.dkr.ecr.us-east-1.amazonaws.com/flocal
  post_build:
    commands:
      - docker push 296274010522.dkr.ecr.us-east-1.amazonaws.com/flocal
      - printf '[{"name":helloWorld,"imageUri":"%s"}]' 296274010522.dkr.ecr.us-east-1.amazonaws.com/flocal > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
